import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import theme from "./theme";
import { CssBaseline, InitColorSchemeScript } from "@mui/material";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import AnimatedBackground from "./components/Background/AnimatedBackground";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "OmarTemsah-Dev-Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialMode = "dark";

  return (
    <html lang="en" className={roboto.variable} suppressHydrationWarning>
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <InitColorSchemeScript
            attribute="class"
            defaultMode="system"
            modeStorageKey="mui-mode"
          />
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Navbar />
            <AnimatedBackground initialMode={initialMode}>
              {children}
            </AnimatedBackground>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
